jobs:
  login-to-azure:
    executor: azure-cli/azure-docker
    steps:
      - checkout
      - azure-cli/login-with-service-principal
      - run: echo $BUILD_ENV
      - run:
          name: privision environment
          command: |
            ls -l
            if $NEW_ENV; then
              if [ "$BUILD_ENV" = "Dev" ]; then
                az deployment sub create --subscription $SUBSCRIPTION_ID --location eastus --template-file Infrastructure-Code/ResourceGroup/resourcegroup.json --parameters rgLocation=eastus rgName=DEV-RG environment=Dev project=Shield
              elif [ "$BUILD_ENV" = "SIT" ]; then
                az deployment sub create --subscription $SUBSCRIPTION_ID --location eastus --template-file Infrastructure-Code/ResourceGroup/resourcegroup.json --parameters rgLocation=eastus rgName=SIT-RG environment=SIT project=Shield
              fi
            fi
      - run: echo 0               

orbs:
  azure-cli: circleci/azure-cli@1.0.0
version: 2.1
workflows:
  example-workflow:
    jobs:
      - login-to-azure:
          context:
            - Shield

      