jobs:
  login-to-azure:
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal
      - run: echo "<< parameters.should_build >>"
      - run: echo $BUILD_ENV
      - run:
          name: privision environment
          command: |
            if $NEW_ENV; then
              if [ "$BUILD_ENV" = "Dev" ]; then
                az resource list
              elif [ "$BUILD_ENV" = "SIT" ]; then
                az resource list
              fi
            fi
      - run: echo 0               

orbs:
  azure-cli: circleci/azure-cli@1.0.0
version: 2.1
workflows:
  example-workflow:
    jobs:
      - login-to-azure:
          context:
            - Shield

      