jobs:
  login-to-azure:
    executor: azure-cli/azure-docker
    steps:
      - checkout
      - azure-cli/login-with-service-principal
      - run: echo $BUILD_ENV
      - run:
          name: privision environment
          command: |
            ls -l
            if $NEW_ENV; then
              if [ "$BUILD_ENV" = "Dev" ]; then
                az deployment sub create --subscription $SUBSCRIPTION_ID --location eastus --template-file Infrastructure-Code/ResourceGroup/resourcegroup.json --parameters rgLocation=eastus rgName=$RESOURCE_GROUP_NAME environment=Dev project=Shield
                az deployment group create --resource-group $RESOURCE_GROUP_NAME --subscription $SUBSCRIPTION_ID --template-file Infrastructure-Code/VirtualNetwork/virtualnetwork.json --parameters @Infrastructure-Code/VirtualNetwork/virtualnetwork.parameters.json --parameters rgLocation=eastus environment=Dev project=Shield vnetName=VNET-DEV vnetAddressCIDR=10.100.0.0/24 functionappSubnetCIDR=10.100.0.0/25 apimSubnetCIDR=10.100.0.128/25
              elif [ "$BUILD_ENV" = "SIT" ]; then
                az deployment sub create --subscription $SUBSCRIPTION_ID --location eastus --template-file Infrastructure-Code/ResourceGroup/resourcegroup.json --parameters rgLocation=eastus rgName=SIT-RG environment=SIT project=Shield
                az deployment group create --resource-group $RESOURCE_GROUP_NAME --subscription $SUBSCRIPTION_ID --template-file Infrastructure-Code/VirtualNetwork/virtualnetwork.json --parameters @Infrastructure-Code/VirtualNetwork/virtualnetwork.parameters.json --parameters rgLocation=eastus environment=SIT project=Shield vnetName=VNET-SIT vnetAddressCIDR=10.100.0.0/24 functionappSubnetCIDR=10.100.0.0/25 apimSubnetCIDR=10.100.0.128/25
              fi
            fi

orbs:
  azure-cli: circleci/azure-cli@1.0.0
version: 2.1
workflows:
  example-workflow:
    jobs:
      - login-to-azure:
          context:
            - Shield

      