jobs:
  login-to-azure:
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal
      - run:
          command: az resource list
          name: List resources of tenant stored as `AZURE_SP_TENANT` env var
orbs:
  azure-cli: circleci/azure-cli@1.0.0
version: 2.1
workflows:
  example-workflow:
    jobs:
      - example-workflow:
          context:
            - Shield
      - login-to-azure
      