jobs:
  login-to-azure:
    executor: azure-cli/azure-docker
    parameters:
      env_build:
        type: string
        default: ""
      should_build:
        type: string
        default: ""        
    steps:
      - when:
          condition: << parameters.should_build >>        
          steps:
            - when:
                condition: 
                  equal: [ Dev, << parameters.env_build >> ]
                steps:
                  - azure-cli/login-with-service-principal
                  - run:
                      command: az resource list
                      name: List resources of tenant stored as `AZURE_SP_TENANT` env var for Dev environment


orbs:
  azure-cli: circleci/azure-cli@1.0.0
version: 2.1
workflows:
  example-workflow:
    jobs:
      - login-to-azure:
          context:
            - Shield
          should_build: "$NEW_ENV"  
          env_build: "$BUILD_ENV"
      